/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_enet_ENetConnection */

#ifndef _Included_com_enet_ENetConnection
#define _Included_com_enet_ENetConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_enet_ENetConnection_nativeInitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeDeinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_enet_ENetConnection_nativeDeinitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeCreateHost
 * Signature: (Ljava/lang/String;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_enet_ENetConnection_nativeCreateHost
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeCreateHostBound
 * Signature: (Ljava/lang/String;IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_enet_ENetConnection_nativeCreateHostBound
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeConnect
 * Signature: (JLjava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_enet_ENetConnection_nativeConnect
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeService
 * Signature: (JI)Lcom/enet/ENetEvent;
 */
JNIEXPORT jobject JNICALL Java_com_enet_ENetConnection_nativeService
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeSend
 * Signature: (JJB[BI)I
 */
JNIEXPORT jint JNICALL Java_com_enet_ENetConnection_nativeSend
  (JNIEnv *, jobject, jlong, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeBroadcast
 * Signature: (JB[BI)V
 */
JNIEXPORT void JNICALL Java_com_enet_ENetConnection_nativeBroadcast
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeFlush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_enet_ENetConnection_nativeFlush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeDisconnectPeer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_enet_ENetConnection_nativeDisconnectPeer
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_enet_ENetConnection
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_enet_ENetConnection_nativeDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif

